# Generated by Django 2.1.7 on 2019-03-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_info',
            name='country',
            field=models.CharField(default='0', max_length=19),
        ),
        migrations.AddField(
            model_name='profile_info',
            name='county',
            field=models.CharField(default='0', max_length=19),
        ),
        migrations.AddField(
            model_name='profile_info',
            name='postal_code',
            field=models.CharField(default='0', max_length=19),
        ),
        migrations.AlterField(
            model_name='profile_info',
            name='address',
            field=models.CharField(default='0', max_length=19),
        ),
    ]
