# Generated by Django 2.1.7 on 2019-03-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190329_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_info',
            name='account',
            field=models.CharField(max_length=20),
        ),
    ]
