# Generated by Django 2.1.7 on 2019-04-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_info',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default='0', max_length=19),
        ),
        migrations.AddField(
            model_name='account',
            name='county',
            field=models.CharField(default='0', max_length=19),
        ),
        migrations.AddField(
            model_name='account',
            name='postal_code',
            field=models.CharField(default='0', max_length=19),
        ),
        migrations.DeleteModel(
            name='Profile_info',
        ),
    ]
