# Generated by Django 2.1.7 on 2019-04-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190406_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='amount',
            new_name='Account_Balance',
        ),
    ]
