# Generated by Django 2.1.7 on 2019-04-06 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20190406_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Kenya', max_length=200)),
                ('address', models.CharField(default='0000', max_length=19)),
                ('postal_code', models.CharField(default='0000', max_length=19)),
                ('county', models.CharField(default='Nairobi', max_length=19)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='county',
        ),
        migrations.RemoveField(
            model_name='account',
            name='postal_code',
        ),
    ]
