# Generated by Django 2.1.4 on 2019-01-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsell',
            old_name='author',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='postsell',
            name='content',
        ),
        migrations.AddField(
            model_name='postsell',
            name='commodity',
            field=models.ImageField(default='default_commodity.jpeg', upload_to='commodity_pics'),
        ),
        migrations.AddField(
            model_name='postsell',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='postsell',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='postsell',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
