# Generated by Django 2.1.4 on 2019-01-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20190101_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsell',
            name='commodity',
            field=models.ImageField(null=True, upload_to='commodity_pics'),
        ),
    ]
