# Generated by Django 2.1.4 on 2019-01-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20190101_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsell',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
