# Generated by Django 2.1.4 on 2019-01-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20190101_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsell',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
