# Generated by Django 2.1.4 on 2019-01-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20190101_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsell',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
