# Generated by Django 2.1.4 on 2019-01-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20190103_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsell',
            name='commodity',
            field=models.ImageField(default='', upload_to='commodity_pics'),
        ),
        migrations.AlterField(
            model_name='postsell',
            name='description',
            field=models.TextField(default='kindly input product description'),
        ),
        migrations.AlterField(
            model_name='postsell',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
