# Generated by Django 2.1.4 on 2019-01-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20190103_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsell',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='postsell',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
    ]
