# Generated by Django 2.1.4 on 2019-01-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20190104_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsell',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
