# Generated by Django 2.1.4 on 2019-01-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20190106_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsell',
            name='commodity',
        ),
    ]
