# Generated by Django 2.1.4 on 2019-01-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_remove_postsell_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsell',
            name='commodity',
            field=models.ImageField(blank=True, null=True, upload_to='commodity_pics'),
        ),
    ]
