# Generated by Django 2.1.4 on 2019-01-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_postsell_commodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsell',
            name='commodity',
            field=models.ImageField(default='default.jpg', null=True, upload_to='commodity_pics'),
        ),
    ]
