# Generated by Django 2.1.4 on 2019-01-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20190106_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsell',
            name='commodity',
            field=models.ImageField(default='', upload_to='commodity_pics'),
        ),
    ]
