# Generated by Django 2.1.4 on 2019-01-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20190106_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsell',
            name='commodity',
        ),
    ]
