# Generated by Django 2.1.4 on 2019-01-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_remove_postsell_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsell',
            name='commodity',
            field=models.ImageField(default='', upload_to='commodity_pics'),
        ),
    ]
