# Generated by Django 2.1.4 on 2019-01-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_postsell_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsell',
            name='time',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
