# Generated by Django 2.1.4 on 2019-01-08 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_postsell_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsell',
            name='live_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
