# Generated by Django 2.1.4 on 2019-01-08 07:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_postsell_live_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsell',
            name='live_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 7, 26, 29, 291856, tzinfo=utc)),
        ),
    ]
