# Generated by Django 2.1.4 on 2019-01-12 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0021_auto_20190108_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='postsell',
            name='live_date',
        ),
        migrations.RemoveField(
            model_name='postsell',
            name='time',
        ),
        migrations.AlterField(
            model_name='postsell',
            name='commodity',
            field=models.ImageField(default='', upload_to='commodity_pics', verbose_name='describe the item'),
        ),
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.PostSell'),
        ),
    ]
