# Generated by Django 2.1.5 on 2019-01-17 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_auto_20190112_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postsell',
            name='commodity',
            field=models.ImageField(default='', upload_to='commodity_pics', verbose_name='Let the buyer see what you are selling, upload a picture'),
        ),
        migrations.AlterField(
            model_name='postsell',
            name='description',
            field=models.TextField(default='', verbose_name='Input some description of the item'),
        ),
        migrations.AlterField(
            model_name='postsell',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='How much are you selling the item for?'),
        ),
        migrations.AlterField(
            model_name='postsell',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Input the name of the Item you are selling'),
        ),
    ]
