# Generated by Django 2.1.4 on 2019-01-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_auto_20190119_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('20', '20'), ('30', '30')], default='5', max_length=20),
        ),
    ]
