# Generated by Django 2.1.4 on 2019-01-20 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0028_auto_20190119_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsell',
            name='live_time',
            field=models.CharField(choices=[('5 minutes', '5'), ('10 minutes', '10'), ('20 minutes', '20'), ('30 minutes', '30')], default='5', max_length=20, verbose_name='How long should your item stay in the auction table?'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
