# Generated by Django 2.1.4 on 2019-01-20 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0029_auto_20190120_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsell',
            name='sell_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
