# Generated by Django 2.1.4 on 2019-01-20 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0030_postsell_sell_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsell',
            name='sell_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
