# Generated by Django 2.1.4 on 2019-01-23 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0033_auto_20190123_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsell',
            old_name='commodity',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='bidder',
            name='bid_amount',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric are allowed.')]),
        ),
    ]
