# Generated by Django 2.1.4 on 2019-01-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0034_auto_20190123_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsell',
            name='owner',
        ),
    ]
