# Generated by Django 2.1.4 on 2019-01-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0036_postsell_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsell',
            name='owner',
        ),
    ]
