# Generated by Django 2.1.4 on 2019-01-25 07:34

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('market', '0037_remove_postsell_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostSell',
            new_name='Product',
        ),
    ]
