# Generated by Django 2.1.4 on 2019-01-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0039_auto_20190125_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Painting', 'Painting'), ('Sculpture', 'Sculpture'), ('Book', 'Book'), ('Instrument', 'Instrument')], default='Gen', max_length=100, verbose_name='Choose product category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='live_time',
            field=models.CharField(choices=[('5', '5 minutes'), ('10', '10 minutes'), ('20', '20 minutes'), ('30', '30 minutes'), ('60', '1 Hour')], default='5', max_length=20, verbose_name='How long should your item stay in the auction table?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=10, verbose_name='What is the least price you are selling your item for?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Input the title of the Item you are selling'),
        ),
    ]
