# Generated by Django 2.1.4 on 2019-01-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0041_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
