# Generated by Django 2.1.4 on 2019-02-01 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0044_remove_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user_name',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
