# Generated by Django 2.1.4 on 2019-02-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0049_auto_20190222_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='What is the least price you are selling your item for?'),
        ),
    ]
