# Generated by Django 2.1.4 on 2019-03-17 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0050_auto_20190222_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sell_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='When do you want your item to go live for Auction?'),
        ),
    ]
