# Generated by Django 2.1.4 on 2019-03-17 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0051_auto_20190317_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sell_on',
        ),
        migrations.AddField(
            model_name='product',
            name='sell_on_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='When do you want your item to go live for Auction? (YYY-MM-DD)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_on_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='What time would you like your item to go live for Auction'),
        ),
    ]
