# Generated by Django 2.1.4 on 2019-03-17 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0054_product_sell_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sell_time',
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='When do you want your item to go live for Auction?'),
        ),
    ]
