# Generated by Django 2.1.4 on 2019-03-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0055_auto_20190317_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='bid_status',
            field=models.TextField(default='Pending'),
        ),
    ]
