# Generated by Django 2.1.4 on 2019-03-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0056_bidder_bid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='bid_status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Winner')], default='0', max_length=2),
        ),
    ]
