# Generated by Django 2.1.4 on 2019-03-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0057_auto_20190317_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='bid_status',
            field=models.CharField(choices=[('PENDING', '0'), ('WINNER', '1')], default='PENDING', max_length=20),
        ),
    ]
