# Generated by Django 2.1.7 on 2019-03-30 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0062_auto_20190330_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='live_time',
            field=models.CharField(choices=[('5', '5 minutes'), ('10', '10 minutes'), ('20', '20 minutes'), ('30', '30 minutes'), ('60', '1 Hour')], default='5', max_length=20, verbose_name='How long should your item stay in the auction table?'),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
