# Generated by Django 2.1.7 on 2019-03-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0064_auto_20190330_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='live_time',
            field=models.CharField(choices=[('0', '0 minutes'), ('1', '1 minutes'), ('5', '5 minutes'), ('10', '10 minutes'), ('20', '20 minutes'), ('30', '30 minutes'), ('60', '1 Hour')], default='5', max_length=20, verbose_name='How long should your item stay in the auction table?'),
        ),
    ]
