# Generated by Django 2.1.7 on 2019-04-06 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0066_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.CharField(default=100000, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric are allowed.')]),
        ),
    ]
