# Generated by Django 2.1.7 on 2019-04-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0068_auto_20190406_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cardNumber',
            field=models.CharField(default='AUCT-010', max_length=30),
        ),
    ]
