# Generated by Django 2.2 on 2019-04-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0074_auto_20190429_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Painting', 'Painting'), ('Sculpture', 'Sculpture'), ('Book', 'Book'), ('Instrument', 'Instrument'), ('Milk', 'Milk'), ('Tea', 'Tea'), ('Maize', 'Maize')], default='Gen', max_length=100, verbose_name='Choose product type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Agriculture', 'Agriculture')], default='Gen', max_length=100, verbose_name='Choose product category'),
        ),
    ]
