# Generated by Django 2.2 on 2019-04-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0075_auto_20190429_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Relic', 'Relic'), ('Agriculture', 'Agriculture')], default='Gen', max_length=100, verbose_name='Choose product category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='live_time',
            field=models.CharField(choices=[('5', '5 minutes'), ('10', '10 minutes'), ('30', '30 minutes'), ('60', '1 Hour'), ('720', '1 month'), ('1440', '2 months'), ('2160', '3 Months')], default='5', max_length=20, verbose_name='How long should your item stay in the auction table?'),
        ),
    ]
